# Generated by Django 3.2.4 on 2021-07-19 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_alter_profile_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Адресс')),
                ('location', models.TextField(verbose_name='location')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.TextField(default=1, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Tg ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ugc.departments', verbose_name='Department'),
            preserve_default=False,
        ),
    ]
