# Generated by Django 3.2.4 on 2021-07-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_auto_20210719_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='student',
            name='suit',
            field=models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], default=1),
            preserve_default=False,
        ),
    ]
