# Generated by Django 3.2.4 on 2021-07-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_auto_20210719_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
