# Generated by Django 3.2.4 on 2021-07-19 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0006_auto_20210719_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ugc.departments', verbose_name='department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departments',
            name='location',
            field=models.TextField(verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='title',
            field=models.TextField(verbose_name='title'),
        ),
    ]
