# Generated by Django 3.2.4 on 2021-07-19 12:45

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone 

class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0007_auto_20210719_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Тайтл вопроса')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='NeedTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now(), verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.TextField(choices=[('REQUESTED', 'REQUESTED'), ('JOINED', 'JOINED'), ('BLOCKED', 'BLOCKED')], default='REQUESTED', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='StatusedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время Изменения')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.profile', verbose_name='Модератор')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='REQUESTED', max_length=20, verbose_name='status')),
                ('need', models.TextField(verbose_name='Text')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время Отправки')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.departments', verbose_name='department')),
                ('need_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.needtypes', verbose_name='Need type')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.profile', verbose_name='Отправитель Зопроса')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
