# Generated by Django 3.2.4 on 2021-07-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0008_auto_20210719_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='needtypes',
            options={'verbose_name': 'Нужда', 'verbose_name_plural': 'Нужды'},
        ),
        migrations.AlterModelOptions(
            name='statusedby',
            options={'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='created_at',
            new_name='send_at',
        ),
        migrations.AlterField(
            model_name='departments',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.departments', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Телеграм ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.TextField(choices=[('REQUESTED', 'REQUESTED'), ('JOINED', 'JOINED'), ('BLOCKED', 'BLOCKED')], default='REQUESTED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.departments', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='need',
            field=models.TextField(verbose_name='Описание Нужды'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='need_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.needtypes', verbose_name='Тип Нужды'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.TextField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='REQUESTED', max_length=20, verbose_name='Статус'),
        ),
    ]
