# Generated by Django 3.2.4 on 2021-07-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0009_auto_20210719_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name': 'Зопрос', 'verbose_name_plural': 'Зопросы'},
        ),
    ]
