# Generated by Django 3.1 on 2021-08-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0012_auto_20210729_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message_id',
            field=models.IntegerField(unique=True, verbose_name='ID Сообщения'),
        ),
    ]
