# Generated by Django 3.1 on 2021-08-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0013_profile_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='message_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='ID Сообщения'),
        ),
    ]
