# Generated by Django 3.1 on 2021-08-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0015_auto_20210805_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='message_id',
            field=models.IntegerField(default=10, unique=True, verbose_name='ID Сообщения'),
        ),
    ]
