# Generated by Django 3.1 on 2021-08-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0018_auto_20210805_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='message_id',
        ),
    ]
