# Generated by Django 3.1 on 2021-08-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0019_remove_requests_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='message_id',
            field=models.IntegerField(default=100, unique=True, verbose_name='ID Сообщения'),
        ),
    ]
