# Generated by Django 3.1 on 2021-08-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0020_requests_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='reply_to',
            field=models.IntegerField(default=200, unique=True, verbose_name='ID для Ответа '),
        ),
    ]
