# Generated by Django 3.1 on 2021-08-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0021_requests_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='reply_to',
            field=models.IntegerField(default=200, verbose_name='ID для Ответа '),
        ),
    ]
