# Generated by Django 3.1 on 2021-08-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0022_auto_20210805_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='reply_to',
        ),
    ]
