# Generated by Django 3.1 on 2021-08-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0025_auto_20210805_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='message_id',
            field=models.IntegerField(default=100, unique=True, verbose_name='ID Сообщения от Админ '),
        ),
        migrations.AlterField(
            model_name='requests',
            name='reply_to',
            field=models.IntegerField(default=200, unique=True, verbose_name='ID Запроса'),
        ),
    ]
