# Generated by Django 3.1 on 2021-08-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0026_auto_20210805_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='reply_to',
            new_name='reply_to_message_id',
        ),
    ]
